# --- Server ---
server.port=${PORT:4000}

# --- MySQL (default profile) ---
spring.datasource.url=${SPRING_DATASOURCE_URL=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/facedb?sslMode=VERIFY_IDENTITYfacedb?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ZC5fiyoLs7pASYG.root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- File uploads ---
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
app.upload-dir=${APP_UPLOAD_DIR:uploads}

# --- JWT ---
app.jwt.secret=${APP_JWT_SECRET:9f8365e544e4fd3fe196b72483937e28}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:3600000}
